# Definition: AdvancedBloomSettingsOptionalFieldMapDefaults
# Hash: fe183d60
# Flags: 0x300

0x0: flBloomWeight0 # DT_FLOAT (32 bits used)
0x4: flBloomWeight1 # DT_FLOAT (32 bits used)
0x8: flBloomWeight2 # DT_FLOAT (32 bits used)
0xc: flBloomWeight3 # DT_FLOAT (32 bits used)
0x10: flBloomWeight4 # DT_FLOAT (32 bits used)
0x14: flBloomWeight5 # DT_FLOAT (32 bits used)
0x18: rgbaBloomTint0 # DT_RGBACOLOR (32 bits used)
0x1c: rgbaBloomTint1 # DT_RGBACOLOR (32 bits used)
0x20: rgbaBloomTint2 # DT_RGBACOLOR (32 bits used)
0x24: rgbaBloomTint3 # DT_RGBACOLOR (32 bits used)
0x28: rgbaBloomTint4 # DT_RGBACOLOR (32 bits used)
0x2c: rgbaBloomTint5 # DT_RGBACOLOR (32 bits used)
0x30: null or eof # DT_NULL
