# Definition: CollisionSettings
# Hash: b6c4d1fd
# Flags: 0x30a

0x0: snoCollision # DT_SNO (32 bits used) {group 0x7f "CollisionSettings"}
0x4: tCustomCollFlags # ActorCollisionFlags
0xc: unk_a882afd # DT_INT (1 bits used)
0x10: unk_54403ff # DT_INT (1 bits used)
0x14: null or eof # DT_NULL
