# Definition: DotApplicationVisualsMessage
# Hash: c40ea787
# Flags: 0x100

0x0: tHeader # RequiredMessageHeader
0x10: snoPower # DT_SNO (32 bits used) {group 0x1d "Power"}
0x14: dwPayloadDataID # DT_UINT (32 bits used)
0x18: eDamageType # DT_ENUM (3 bits used)
0x1c: annTarget # DT_ACD_NETWORK_NAME (64 bits used)
0x24: annAttacker # DT_ACD_NETWORK_NAME (64 bits used)
0x2c: unk_1c7ccc9 # DT_FLOAT (32 bits used)
0x30: bTargetAlive # DT_INT (1 bits used)
0x34: vLocalImpactPos # DT_OPTIONAL => DT_VECTOR3D
0x44: vProjectileImpactDirection # DT_OPTIONAL => DT_VECTOR3D
0x54: flImpactDirection # DT_OPTIONAL (32 bits used) => DT_FLOAT
0x5c: flImpactPitch # DT_OPTIONAL (32 bits used) => DT_FLOAT
0x64: null or eof # DT_NULL
