# Definition: FoliageSettings
# Hash: 12daec08
# Flags: 0x30a

0x0: flExplosionFactor # DT_FLOAT (32 bits used)
0x4: flFrequency # DT_FLOAT (32 bits used)
0x8: flDampingRatio # DT_FLOAT (32 bits used)
0xc: flMaxOffsetFactor # DT_FLOAT (32 bits used)
0x10: flRadiusRatio # DT_FLOAT (32 bits used)
0x14: snoSoundDisturbed # DT_SNO (32 bits used) {group 0x28 "Sound"}
0x18: snoSoundImpact # DT_SNO (32 bits used) {group 0x28 "Sound"}
0x1c: snoAmbientSound # DT_SNO (32 bits used) {group 0x5 "AmbientSound"}
0x20: unk_620b5c3 # DT_FLOAT (32 bits used)
0x24: unk_bf229f9 # DT_FLOAT (32 bits used)
0x28: null or eof # DT_NULL
