# Definition: HeightFieldWaveSettings
# Hash: 4a900441
# Flags: 0x302

0x0: flMinWaveLength # DT_FLOAT (32 bits used)
0x4: flMaxWaveLength # DT_FLOAT (32 bits used)
0x8: flAmplitudeRatio # DT_FLOAT (32 bits used)
0xc: unk_12070ce # DT_FLOAT (32 bits used)
0x10: null or eof # DT_NULL
