# Definition: LightingDepthSettings
# Hash: 2d18fb5c
# Flags: 0x302

0x0: unk_50f7690 # DT_UINT (32 bits used)
0x4: unk_29377d2 # DT_UINT (32 bits used)
0x8: unk_cd68eaf # DT_UINT (32 bits used)
0xc: dwLightingDepthLimit # DT_UINT (32 bits used)
0x10: null or eof # DT_NULL
