# Definition: NitSettings
# Hash: 220eeabc
# Flags: 0x302

0x0: flNitMin # DT_FLOAT (32 bits used)
0x4: flNitMax # DT_FLOAT (32 bits used)
0x8: rgbaColors # DT_FIXEDARRAY (32 bits used) [7 array size] => DT_RGBACOLOR
0x24: null or eof # DT_NULL
