# Definition: ParametricSettings
# Hash: 39274139
# Flags: 0x302

0x0: fCavity # DT_INT (1 bits used)
0x4: eCavityMode # DT_ENUM (32 bits used)
0x8: flCavityTolerance # DT_FLOAT (32 bits used)
0xc: flCavitySmoothness # DT_FLOAT (32 bits used)
0x10: fHeight # DT_INT (1 bits used)
0x14: flHeightMin # DT_FLOAT (32 bits used)
0x18: flHeightMinSmoothness # DT_FLOAT (32 bits used)
0x1c: flHeightMax # DT_FLOAT (32 bits used)
0x20: flHeightMaxSmoothness # DT_FLOAT (32 bits used)
0x24: fSlope # DT_INT (1 bits used)
0x28: flSlopeMin # DT_FLOAT (32 bits used)
0x2c: flSlopeMinSmoothness # DT_FLOAT (32 bits used)
0x30: flSlopeMax # DT_FLOAT (32 bits used)
0x34: flSlopeMaxSmoothness # DT_FLOAT (32 bits used)
0x38: fDirection # DT_INT (1 bits used)
0x3c: flDirectionAltitude # DT_FLOAT (32 bits used)
0x40: flDirectionAzimuth # DT_FLOAT (32 bits used)
0x44: flDirectionTolerance # DT_FLOAT (32 bits used)
0x48: flDirectionSmoothness # DT_FLOAT (32 bits used)
0x4c: fNoise # DT_INT (1 bits used)
0x50: flNoiseFrequency # DT_FLOAT (32 bits used)
0x54: flNoiseTileDistance # DT_FLOAT (32 bits used)
0x58: flNoiseMin # DT_FLOAT (32 bits used)
0x5c: flNoiseMax # DT_FLOAT (32 bits used)
0x60: vNoiseOffset # DT_VECTOR2D
0x68: fDistanceToWater # DT_INT (1 bits used)
0x6c: flDistanceToWaterMin # DT_FLOAT (32 bits used)
0x70: flDistanceToWaterMinSmoothness # DT_FLOAT (32 bits used)
0x74: flDistanceToWaterMax # DT_FLOAT (32 bits used)
0x78: flDistanceToWaterMaxSmoothness # DT_FLOAT (32 bits used)
0x7c: fInvert # DT_INT (1 bits used)
0x80: null or eof # DT_NULL
