# Definition: ShoreWaveSettings
# Hash: 1d308425
# Flags: 0x302

0x0: unk_4d19a78 # DT_FLOAT (32 bits used)
0x4: flShoreSpeed # DT_FLOAT (32 bits used)
0x8: flShoreMultiplier # DT_FLOAT (32 bits used)
0xc: flWaveSpeed # DT_FLOAT (32 bits used)
0x10: flLineWidth # DT_FLOAT (32 bits used)
0x14: unk_d8d6cc9 # DT_FLOAT (32 bits used)
0x18: unk_503df13 # DT_RANGE => DT_FLOAT
0x20: null or eof # DT_NULL
