# Definition: SkyColorSettingsOptionalFieldMapDefaults
# Hash: af6bc267
# Flags: 0x300

0x0: flHaze # DT_FLOAT (32 bits used)
0x4: unk_b61e136 # DT_FLOAT (32 bits used)
0x8: unk_6fc9e50 # DT_RGBACOLOR (32 bits used)
0xc: unk_3a37ef6 # DT_RGBACOLOR (32 bits used)
0x10: unk_bbf28fc # DT_INT (1 bits used)
0x14: flSunDiskAltitude # DT_FLOAT (32 bits used)
0x18: flSunDiskAzimuth # DT_FLOAT (32 bits used)
0x1c: flSunIntensityFactor # DT_FLOAT (32 bits used)
0x20: unk_cb0e626 # DT_FLOAT (32 bits used)
0x24: unk_cb0e528 # DT_FLOAT (32 bits used)
0x28: unk_467a561 # DT_FLOAT (32 bits used)
0x2c: unk_d4fb023 # DT_FLOAT (32 bits used)
0x30: null or eof # DT_NULL
