# Definition: SlowAmountSettings
# Hash: ee06628a
# Flags: 0x302

0x0: flLight # DT_FLOAT (32 bits used)
0x4: flMedium # DT_FLOAT (32 bits used)
0x8: flHeavy # DT_FLOAT (32 bits used)
0xc: null or eof # DT_NULL
