# Definition: StarsSettingsOptionalFieldMapDefaults
# Hash: 71d9d83e
# Flags: 0x300

0x0: flStarsDensity # DT_FLOAT (32 bits used)
0x4: flStarsDistance # DT_FLOAT (32 bits used)
0x8: flStarsScale # DT_FLOAT (32 bits used)
0xc: flStarsRandomness # DT_FLOAT (32 bits used)
0x10: flStarsBrightness # DT_FLOAT (32 bits used)
0x14: flStarsColor # DT_RGBACOLOR (32 bits used)
0x18: null or eof # DT_NULL
